### ISSUE TITLE
Mock-up Home Page

### ISSUE THREAD

**Issue by MikePulsiferDOL** [USDepartmentofLabor/Developer#7]
Mock-up the new home page.

**Comment by waltcerna** [comment]
@spoonstein here is the new menu on the homepage.
![dol_dev_mockup10](https://cloud.githubusercontent.com/assets/1934400/5599040/5432645e-928e-11e4-8c29-f4d63bfbbeb4.jpg)

**Comment by spoonstein** [comment]
@waltcerna thanks! Please swap CPI and Labor Stats blocks.

**Comment by waltcerna** [comment]
@spoonstein Edits made.
![dol_dev_mockup11](https://cloud.githubusercontent.com/assets/1934400/5599137/e58ae5ec-928f-11e4-8e16-de966f48b34f.jpg)

**Comment by jfc3-dol** [comment]
I suggest we left align the text under the following headings: "Labor Stats", "Consumer Price Index", and the smaller sections "Grab Our Code". Doing so will make it easier for all to read quickly and easily, even move so for those with reading issues such as dyslexia.  

Here are a few resources:

http://uxmovement.com/content/why-you-should-never-center-align-paragraph-text/ 
http://wmich.edu/writing/readability 

jfc iii

**Comment by jfc3-dol** [comment]
If the "API Keys" call to action is to stay in its current position it should have more contrast from the light gray background in the navigation. Plus, this call to action button is dark blue were the other call to actions buttons on the page were black or dark gray.

Part of the problem could be that image below it is dark in the upper right corner which is making it seem not to stand out.

We might want to move it down onto the image, but then it will be competing with the two other call to action buttons.

**Comment by jfc3-dol** [comment]
I think the two call to action buttons on the first image should be bigger so people will notice them along with improving the color contrast so that they will be noticed more.

jfc iii

**Comment by jfc3-dol** [comment]
We should make sure the color contrast of both the text and call to action button for the "Consumer Price Index" should be improved so people can read it better.

jfc iii

**Comment by jfc3-dol** [comment]
Not sure if we should move the smaller heading under the "Grab Our Code" section should be moved on top of the images to help break things up a bit.

Plus, we should make sure to update the call to action button text, so it is not all the same.
jfc iii

**Comment by jfc3-dol** [comment]
One last little detail it might make sense if we can re-create the image of the three phones under the "Labor Stats" section so the text on the phones points left instead of right. In the Unites States, most people read left to right, so it's helpful to have people look into your image from left to right as well. Doing so will help stop the person trying to look off screen.

jfc iii

**Comment by neilneyman** [comment]
@waltcerna Can someone please post, send, or point me toward the graphics & image files?

**Comment by jfc3-dol** [comment]
One point, we should think about for all these comps, is we should use the template and CSS Shirley has built. Doing this will help us make the pages responsive, along with taking a lot of the guess work out of browser testing, etc.

We might have to make a few overrides to the CSS to get the look we are going for, but it's a great start.

jfc iii

**Comment by teo-siewwah** [comment]
Here is my feed back on the homepage mockup:

- Call of action: Add different color backgrounds on the buttons something like this
http://www.swebapps.com/.  Colors buttons help to improve interest, the visibility and differentiate the options. 
- Labor Stats and Consumer Price Index, there are examples from the GRAB OUR CODE section
- For consistency, add brief description so that user at least know what this section is about.
- Add color (can be different colors or same color) on icons just like the colored icons on DIVE INTO OUT DATASETS
